name: small_husn_muslim
description: "A new Flutter project."
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  audio_video_progress_bar: ^2.0.1
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  get: ^4.6.6
  just_audio: ^0.10.4
  path_provider: ^2.1.2
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  simple_icons: ^14.6.1
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/hisnmuslim.json
    - assets/custom_dikr.json
    - assets/sabha.png
    - assets/counterBG.png
    - assets/appBarBG.jpg
    - assets/ic_launcher.png

  fonts:
    - family: AmiriQuran
      fonts:
        - asset: fonts/AmiriQuran-Regular.ttf

    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
