name: small_husn_muslim
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  audio_video_progress_bar: ^2.0.1
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  image_gallery_saver_plus: ^4.0.1
  get: ^4.6.6
  just_audio: ^0.10.5
  path_provider: ^2.1.2
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  simple_icons: ^14.6.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/hisnmuslim.json
    - assets/sabha.png
    - assets/counterBG.png
    - assets/appBarBG.jpg
    - assets/ic_launcher.png

  fonts:
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
